### ISSUE TITLE
Add C# Code Formatter

### ISSUE THREAD

**Issue by zackmark29** [AngryCarrot789/sharppad#5]
Thanks for this great tool.
I really like dark mode. Is it possible that you'll add C# code formatter?

**Comment by AngryCarrot789** [comment]
i was planning on making my own text editor, or atleast putting one together one based on the AvelonEdit's one. so hopefully soon there will be one :}

**Comment by zackmark29** [comment]
Oh wow gonna wait for it. I really like to use your theme. But I'm not yet expert with WPF.
I'm still visiting here to check if there's already for Windows Form :)

**Comment by jeffward01** [comment]
> i was planning on making my own text editor (technically this app does, although not really considering TextEditor is just a wrapper around the TextBox class), or atleast putting one together one based on the AvelonEdit's one. so hopefully soon there will be one :}

Very cool! But what is the pupose of this when there are things like: [Dark Theme for NPP](https://github.com/hellon8/VS2019-Dark-Npp) - Personally I have some bias against NPP, mainly because the CIA hacked NPP, so lost all credibility for me.

Source:

* [Notepad++ Issues Fix After CIA Attack Revealed in Vault7 Documents](https://www.hackread.com/wikileaks-vault7-cia-docs-notepad-plus-vlc/
* https://news.ycombinator.com/item?id=13824032
